name: Deployment pipeline

on:
  push:
    branches:
      - master # Use 'main' if your default branch is named 'main'

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20' 
      
      # 1. Install dependencies (Using 'npm ci' for reliability)
      - name: npm ci install
        run: npm ci
        
      # 2. Lint the code (UPDATED: Uses 'npx' and '|| true' to prevent failure)
      - name: Run ESLint
        # '|| true' ensures this step always exits with code 0 (success) even if lint errors are found (exit code 1)
        run: npx eslint . || true
        
      # 3. Build the code
      - name: build
        run: npm run build
        
      # 4. Test the code (This is expected to be the first failing step now)
      - name: test
        run: npm run test
